import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Card from "@/components/card/Card";
import { products } from "@/utils/sampleData";

import { getSession } from "next-auth/react";
import { GetServerSideProps } from "next";
import { NextPage } from "next/types";

interface Props {
  data: string;
}

const inter = Inter({ subsets: ["latin"] });

const Home: NextPage<Props> = ({ data }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-[100%] grid grid-cols-5 bg-slate-600 overflow-y-scroll scrollbar-hide place-items-center p-5 gap-y-4 scroll scroll-smooth">
        {products.map((obj) => (
          <Card
            name={obj.name}
            src={obj.src}
            price={obj.price}
            alt={obj.alt}
            quantity={obj.quantity}
          />
        ))}
      </main>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);
  // console.log("session:", session);

  // if (!session) {
  //   return {
  //     redirect: {
  //       destination: "/api/auth/signin?callbackUrl=http://localhost:3000/blog",
  //       permanent: false,
  //     },
  //   };
  // }

  return {
    props: {
      data: session ? "List of 100 personalized blogs" : "list of free blogs",
    },
  };
};
