import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Card from "@/components/card/Card";
import AdSkySquare from "@/components/ads/AdSkySquare";
import AdNone from "@/components/ads/AdNone";
import { products } from "@/utils/sampleData";

import { getSession } from "next-auth/react";
import { GetServerSideProps } from "next";
import { NextPage } from "next/types";

interface Props {
  data: string;
}

const inter = Inter({ subsets: ["latin"] });

const Home: NextPage<Props> = ({ data }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-[100%] flex justify-center bg-slate-600">
        <div className="h-[100%] grow grid grid-cols-1 xs:grid-cols-2 md:grid-cols-3  lg:grid-cols-4 xl:grid-cols-5 bg-slate-500 overflow-y-scroll scrollbar-hide place-items-center p-5 gap-y-8 scroll scroll-smooth">
          {products.map((obj) => (
            <Card
              name={obj.name}
              src={obj.src}
              price={obj.price}
              alt={obj.alt}
              quantity={obj.quantity}
              key={obj.id}
            />
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);
  return {
    props: {
      data: session ? "List of 100 personalized blogs" : "list of free blogs",
    },
  };
};
